# DATA SCIENCE IN PYTHON WEEK1
## Reading and Writing CSV Files

In [4]:
import csv
with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
#type(mpg)
mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [3]:
type(mpg)

list

In [5]:
len(mpg)

234

In [7]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [8]:
mpg[0]

OrderedDict([('', '1'),
             ('manufacturer', 'audi'),
             ('model', 'a4'),
             ('displ', '1.8'),
             ('year', '1999'),
             ('cyl', '4'),
             ('trans', 'auto(l5)'),
             ('drv', 'f'),
             ('cty', '18'),
             ('hwy', '29'),
             ('fl', 'p'),
             ('class', 'compact')])

In [8]:
%precision 2
sum(float(d['cty']) for d in mpg)/len(mpg)
 

16.86

In [9]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

In [11]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [17]:
CityMpgbyCyl = []
for c in cylinders:
    summpg = 0
    cyltypecount = 0
    for d in mpg:
        if d['cyl'] == c:
            summpg += float(d['cty'])
            cyltypecount += 1
    CityMpgbyCyl.append((c,summpg/cyltypecount))
    
CityMpgbyCyl.sort(key = lambda x:x[1])    
CityMpgbyCyl
    

[('8', 12.57), ('6', 16.22), ('5', 20.50), ('4', 21.01)]

In [18]:
vehicleclass = set(d['class'] for d in mpg)
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [21]:
HwyMpgByClass = []
for t in vehicleclass:
    summpg = 0
    vclasscount = 0
    for d in mpg:
        if d['class'] == t:
            summpg += float(d['hwy'])
            vclasscount += 1
    HwyMpgByClass.append((t,summpg/vclasscount))
HwyMpgByClass.sort(key=lambda x:x[1])
HwyMpgByClass
                         

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

In [25]:
xs = [1,2,3]
ys = map(lambda x:x*2 ,xs)
print(list(ys))

[2, 4, 6]


In [1]:
A= "amit"

In [2]:
print (A[1])

m


In [4]:
A[1] = "b"
print (A[1])

TypeError: 'str' object does not support item assignment

In [5]:
['a','b','c']+[1,2,3]

['a', 'b', 'c', 1, 2, 3]

In [7]:
type(lambda  x:x+1)

function

In [8]:
import numpy as np
test = np.random.randint(0,36,(6,6))

In [9]:
test


array([[33, 14,  0, 16,  1, 35],
       [ 0,  7,  1, 17, 19, 33],
       [19, 24,  1,  8, 19,  7],
       [17, 11, 30, 19,  9,  3],
       [19, 24, 14, 26,  7, 23],
       [ 6, 28, 24, 17, 17, 22]])

In [10]:
test[0:6,::-7]

array([[35],
       [33],
       [ 7],
       [ 3],
       [23],
       [22]])

In [11]:
test[:,::7]

array([[33],
       [ 0],
       [19],
       [17],
       [19],
       [ 6]])

In [12]:
test[::7]

array([[33, 14,  0, 16,  1, 35]])

In [13]:
test.reshape(36)[::7]

array([33,  7,  1, 19,  7, 22])

In [14]:
test


array([[33, 14,  0, 16,  1, 35],
       [ 0,  7,  1, 17, 19, 33],
       [19, 24,  1,  8, 19,  7],
       [17, 11, 30, 19,  9,  3],
       [19, 24, 14, 26,  7, 23],
       [ 6, 28, 24, 17, 17, 22]])

In [15]:
test[2:4,2:4]

array([[ 1,  8],
       [30, 19]])

In [16]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3  %%rub

In [17]:
?range

# Objects and Maps()

In [28]:
class Person:
    department = 'School of Information'
    def set_name(self,new_name):
        self.name = new_name
    def set_location(self,new_location):
        self.location = new_location

In [29]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('USA')
print('{} live in {} and works in the department {}' .format(person.name,person.location,person.department))

Christopher Brooks live in USA and works in the department School of Information


In [30]:
my_list = [number for number in range(0,1000) if number % 2 == 0]

In [31]:
my_list[10]

20